kinoCMS/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    path('', include('theater.urls', namespace='theater')) 
       
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

theater/urls.py
from django.urls import path

from .views import index, affiche, film_detail, news, news_detail

app_name = 'theater'

urlpatterns = [
    path('', index, name='index'),
    path('affiche/', affiche, name='affiche'),
    path('film/<slug:slug>', film_detail, name='film_detail'),
    path('news/', news, name='news'),
    path('news/<slug:slug>', news_detail, name='news_detail')
]

theater/models.py
from django.db import models
from django.urls import reverse
from django.utils.timezone import now

def set_duration(date):
    duration = str(date-now().date())
    return duration


class Film(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    slug = models.SlugField(max_length=150, unique=True)
    poster = models.ImageField(upload_to='uploads/film/film-poster', default='uploads/None/no-img.jpg')
    trailer_youtube_link = models.CharField(null=True, blank=True, max_length=400)
    show_today = models.BooleanField(default=False)
    show_soon = models.BooleanField(default=False)
    show_soon_from_date = models.DateField(null=True, blank=True)
    show_soon_to_date = models.DateField(null=True, blank=True)
    show_now_to_date = models.DateField(null=True, blank=True)
    can_sell_ticket = models.BooleanField(default=True)


    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('theater:film_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name_plural = "Фільми"

class FilmShowSession(models.Model):
    session = models.DateTimeField(null=True, blank=True)
    three_d = models.BooleanField(default=True, verbose_name='3D сеанс')
    film = models.ForeignKey(Film, on_delete=models.CASCADE)
    hall = models.CharField(max_length=20, blank=True)

    def __unicode__(self):
        return u'%s' % self.since.strftime('%Y-%m-%d %H:%M')


class FilmImages(models.Model):
    image = models.ImageField(upload_to='uploads/film/film-gallery', default='uploads/None/no-img.jpg')
    film = models.ForeignKey('Film', blank=True, null=True, on_delete=models.CASCADE)

class FilmDescription(models.Model):
    year = models.CharField(max_length=20)
    genre = models.CharField(max_length=100)
    country = models.CharField(max_length=150)
    director = models.CharField(max_length=150)
    screenwriter = models.CharField(max_length=150)
    producer = models.CharField(max_length=150)
    operator = models.CharField(max_length=150)
    composer = models.CharField(max_length=150)
    budget = models.IntegerField()
    duration = models.CharField(max_length=150)
    age = models.CharField(max_length=10)
    film = models.ForeignKey(Film, on_delete=models.CASCADE)



class News(models.Model):
    title = models.CharField(max_length=200)
    body = models.CharField(max_length=10000)
    image = models.ImageField(upload_to='uploads/news/', default = 'uploads/None/no-img.jpg')
    slug = models.SlugField(unique=True, max_length=250, null=True)
    date = models.DateTimeField(verbose_name='Дата додавання новини', auto_now=True, blank=True, null=True)
    

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Новини"

    def get_short_body(self):
        return self.body[0:100]
    
    def get_absolute_url(self):
        return reverse('theater:news_detail', kwargs={'slug': self.slug})

kinoCMS/forms.py
# from allauth.account.forms import SignupForm, LoginForm
# from django import forms

# class CustomSignupForm(SignupForm):
#     first_name = forms.CharField(max_length=30, label='Ім\'я')
#     last_name = forms.CharField(max_length=30, label='Прізвище')
#     def signup(self, request, user):
#         user.first_name = self.cleaned_data['first_name']
#         user.last_name = self.cleaned_data['last_name']
#         user.save()
#         return user

kinoCMS/views.py
from django.shortcuts import render

def about(request):
    return render(request, 'about.html')

theater/views.py
from django.shortcuts import render
from django.utils.timezone import now, pytz, timedelta
from django.conf import settings

from .models import Film, FilmImages, News, FilmShowSession, FilmDescription

def index(request):
    user_timezone = pytz.timezone(settings.TIME_ZONE)
    context = {
        'films_today': Film.objects.filter(show_today=True),
        'films_soon': Film.objects.filter(show_soon=True),
        'date': now().astimezone(user_timezone)
    }
    return render(request, 'theater/index.html', context)

def affiche(request):
    context = {
        'films': Film.objects.filter(can_sell_ticket=True),
        'films_soon': Film.objects.filter(show_soon=True, can_sell_ticket=False),
    }
    return render(request, 'theater/affiche.html', context)

def film_detail(request, slug):
    film = Film.objects.get(slug=slug)  
    curentdatetime = now().date()
    sessions = FilmShowSession.objects.filter(film__slug=slug)
    description = FilmDescription.objects.filter(film__slug=slug).first()

    context = {
        'description': description,
        'sessions': sessions,
        'film': Film.objects.get(slug=slug),
        'gallery': FilmImages.objects.filter(film__slug=slug),
        'curentdatetime': curentdatetime,
    }
    return render(request, 'theater/film_detail.html', context)



def news(request):
    context = {
        'news': News.objects.all(),
    }
    return render(request, 'theater/news.html', context)

def news_detail(request, slug):
    pass

templates/adminlte/lib/_main_header.html
{% extends 'adminlte/lib/_main_header.html' %}

{% load adminlte_helpers i18n %}
{% load static %}
<nav class="main-header navbar navbar-expand navbar-white navbar-light">


    <!-- Header Navbar: style can be found in header.less -->
    {% block nav_bar %}
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/" class="nav-link">Siiite</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin" class="nav-link">Admin</a>
        </li>
    </ul>

    {% block nav_bar_center %}
    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>
    {% endblock %}

    {% block nav_custom_menu %}
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <ul class="nav navbar-nav">
            {% block header_dropdowns %}
            <!-- Messages Dropdown Menu -->
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-comments fa-2x"></i>
                    <span class="badge badge-danger navbar-badge">3</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <a href="#" class="dropdown-item">
                        <!-- Message Start -->
                        <div class="media">
                            <img src="{%static 'admin-lte/dist/img/user1-128x128.jpg' %}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                            <div class="media-body">
                                <h3 class="dropdown-item-title">
                                    Brad Diesel
                                    <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                                </h3>
                                <p class="text-sm">Call me whenever you can...</p>
                                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                            </div>
                        </div>
                        <!-- Message End -->
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <!-- Message Start -->
                        <div class="media">
                            <img src="{%static 'admin-lte/dist/img/user8-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
                            <div class="media-body">
                                <h3 class="dropdown-item-title">
                                    John Pierce
                                    <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                                </h3>
                                <p class="text-sm">I got your message bro</p>
                                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                            </div>
                        </div>
                        <!-- Message End -->
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <!-- Message Start -->
                        <div class="media">
                            <img src="{%static 'admin-lte/dist/img/user3-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
                            <div class="media-body">
                                <h3 class="dropdown-item-title">
                                    Nora Silvester
                                    <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                                </h3>
                                <p class="text-sm">The subject goes here</p>
                                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                            </div>
                        </div>
                        <!-- Message End -->
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
                </div>
            </li>
            <!-- Notifications Dropdown Menu -->
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-bell fa-2x"></i>
                    <span class="badge badge-warning navbar-badge">15</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-item dropdown-header">15 Notifications</span>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-envelope mr-2"></i> 4 new messages
                        <span class="float-right text-muted text-sm">3 mins</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-users mr-2"></i> 8 friend requests
                        <span class="float-right text-muted text-sm">12 hours</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-file mr-2"></i> 3 new reports
                        <span class="float-right text-muted text-sm">2 days</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                </div>
            </li>
            <!-- Notifications Dropdown Menu -->
            {% block user_info %}
            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="far fa-user fa-2x"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <a href="#" class="dropdown-item">
                            <!-- Message Start -->
                            <div class="media">
                                <img src="{%avatar_url size=128 %}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                                <div class="media-body">
                                    <h3 class="dropdown-item-title">
                                            {% firstof request.user.get_short_name request.user.get_username %}
                                        <span class="float-right text-sm text-danger"><i class="fas fa-online"></i></span>
                                    </h3>
                                    <p class="text-sm"><small>Member since :</small></p>
                                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i>  <small>{{ request.user.date_joined }}</small></p>
                                </div>
                            </div>
                            <!-- Message End -->
                        </a>
                        <div class="dropdown-divider"></div>
                        <div class="dropdown-footer">
                                <a href="{% block change_password_url %}{% url 'admin:password_change' %}{% endblock %}" class="btn btn-primary btn-sm">{% trans 'Change password' %}</a>
                                <a  href="admin/logout" class="btn btn-danger btn-sm">Вихід</a>
                            </div>
                        
                    </div>
                </li>
            {% endif %}
            {% endblock user_info %}
            {% endblock header_dropdowns %}
        </ul>
    </ul>
        {% endblock nav_custom_menu %}

{% endblock %}
</nav>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>kinoCMS</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    
</head>
<body>
    <div class="header-banner" style="height: 100px;">

    </div>
    <header class="container col-10">
        <nav class="nav nav-fill">
            <li class="nav-item">
                <form class="form-inline">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Пошук</button>
                </form>
            </li>
            <li class="nav-item">
                    <a href="#" style="color: blue;"> Facebook <i class="fab fa-facebook"></i> </a>
                    <a href="#" style="color: rgb(105, 194, 230);"> Twitter <i class="fab fa-twitter"></i> </a>
                    <a href="#" style="color: coral;"> Instagram <i class="fab fa-instagram"></i> </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="tel:+380666666666" style="padding: 0;">+380666666666</a>
                <a class="nav-link" href="tel:+380666666666" style="padding: 0;">+380666666666</a>
            </li>
        </nav>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a href="{% url 'theater:index' %}" class="navbar-brand">kinoCMS</a>
            <button class="navbar-toggler" data-target="#my-nav" data-toggle="collapse" aria-controls="my-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="my-nav" class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'theater:affiche' %}">Афіша<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="#" tabindex="-1">Розклад</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="#" tabindex="-1">Скоро</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="#" tabindex="-1">Кінотеатри</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="#" tabindex="-1">Акції</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="#" tabindex="-1">Розклад</a>
                    </li>
                    <div class="dropdown">
                        <button id="my-dropdown" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Про кінотеатр</button>
                        <div class="dropdown-menu" aria-labelledby="my-dropdown">
                            <a class="dropdown-item" href="{% url 'theater:news' %}">Новини</a>
                            <a class="dropdown-item" href="#">Реклама</a>
                            <a class="dropdown-item" href="#">Кафе</a>
                            <a class="dropdown-item" href="#">Мобільні додатки</a>
                            <a class="dropdown-item" href="#">Контакти</a>
                        </div>
                    </div>
                </ul>
                {% if request.user.is_authenticated %}
                <div class="dropdown mr-2">
                    <button id="my-dropdown" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ request.user.username }}</button>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="my-dropdown">
                        {% if request.user.is_staff %}
                            <a class="dropdown-item" href="/admin/">Адмінпанель</a>
                        {% endif %}
                        <a class="dropdown-item" href="#">Особистий кабінет</a>
                        <a class="dropdown-item" href="/accounts/logout">Вихід</a>
                    </div>
                </div>
                {% else %}
                <a href="/accounts/login" class="btn btn-success mr-2">Вхід</a>
                {% endif %}
                <div class="dropdown">
                    <button id="my-dropdown" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">UA</button>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="my-dropdown">
                        <a class="dropdown-item" href="#">RU</a>
                        <a class="dropdown-item" href="#">EN</a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main>
        {% block content %}
    
        {% endblock content %}
    </main>
    <footer class="container col-10">
        <h4 class="text-center header-4">Новини та Акції</h4>
        <div class="news_actions">
            <div id="my-carousel2" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li class="active" data-target="#my-carousel2" data-slide-to="0" aria-current="location"></li>
                    <li data-target="#my-carousel2" data-slide-to="1"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img class="d-block w-100" src="{% static '/img/no_photo.png' %}" alt="">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>Title</h5>
                            <a href="#" class="btn btn-info">
                                Детальніше
                            </a>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="{% static '/img/no_photo.png' %}" alt="">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>Title</h5>
                            <a href="#" class="btn btn-info">
                                Детальніше
                            </a>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#my-carousel2" data-slide="prev" role="button">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#my-carousel2" data-slide="next" role="button">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
        <div class="footer_baner"></div>
        <div class="footer_ceo_text text-center">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ipsam nam sunt, dignissimos placeat fuga rerum quisquam dolorum, ut delectus quidem natus! Consectetur totam pariatur repellat sunt suscipit incidunt vel eum quis itaque, ad sint fuga quisquam impedit enim laudantium! Ullam veritatis animi magni dicta dolorum esse est laboriosam, ab reprehenderit incidunt aliquid placeat iusto blanditiis impedit eveniet, beatae eius iure, architecto neque saepe? Officiis pariatur soluta assumenda eveniet nesciunt eius iste? Temporibus, laudantium fugiat! Illum a esse soluta aut asperiores nam unde quasi at voluptate ea modi nemo, quisquam, nostrum, placeat aspernatur consequuntur cum fuga suscipit? Officiis cum nam sequi voluptates harum dignissimos provident, iste magni ipsa, debitis quidem tempore incidunt, aliquam ut asperiores. Aspernatur neque quidem dolorem voluptatem ipsa quod facere deleniti, atque doloremque excepturi minima rem quibusdam delectus minus sit molestias quae ea consequatur, vel expedita saepe.</p>
        </div>
        <hr>
        <div class="last-block">
            <div class="mobil-app">
                <h5>Мобільні додатки</h5>
                <a href="#"> <img src="#" alt="Google Play"> </a>
                <a href="#"> <img src="#" alt="App Store"> </a>
                <p>Розробка сайтів: AVADA MEDIA</p>
            </div>
            <div class="affiche">
                <h5>Афіша</h5>
                <a class="nav-link" href="#">Розклад</a>
                <a class="nav-link" href="#">Скоро в прокаті</a>
                <a class="nav-link" href="#">Кінотеатри</a>
                <a class="nav-link" href="#">Акції</a>
            </div>
            <div class="about">
                <h5>Про кінотеатр</h5>
                <a class="nav-link" href="#">Новини</a>
                <a class="nav-link" href="#">Реклама</a>
                <a class="nav-link" href="#">Кафе-бар</a>
                <a class="nav-link" href="#">Контакти</a>
            </div>
            <div class="social">
                <a class="nav-link" href="#" style="color: blue;"> Facebook <i class="fab fa-facebook"></i> </a>
                <a class="nav-link" href="#" style="color: rgb(105, 194, 230);"> Twitter <i class="fab fa-twitter"></i> </a>
                <a class="nav-link" href="#" style="color: coral;"> Instagram <i class="fab fa-instagram"></i> </a>
            </div>
        </div>
        <div class="copyright text-center">kinoCMS 2020. All right reserved</div>
    </footer>
    
    <script src="https://kit.fontawesome.com/ecc04f3b39.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/theater/affiche.html
{% extends 'base.html' %}

{% block content %}
<!-- <style>
    a.active{
        background-color: rgb(72, 180, 96)!important;
    }
</style> -->
<div class="container col-11 mt-5">
    <div class="row">
        <div class="col-3">
            <div class="list-group text-center" id="list-tab" role="tablist">
                <a class="list-group-item list-group-item-action active" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">Афіша</a>
                <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">Скоро в прокаті</a>
            </div>
            <div class="side_banner">
                <p>side banner</p>
            </div>
        </div>
        <div class="col-9 bg-dark pt-4 pb-4">
            <div class="tab-content" id="nav-tabContent">
                <div class="tab-pane fade show active" id="list-home" role="tabpanel" aria-labelledby="list-home-list">
                    <div class="card-desk">
                        {% for film in films %}
                            <div class="card" style="width: 15rem;">
                                {% if film.show_soon %}
                                <span class="badge badge-warning text-center" style="font-size: 0.9em;">В прокаті з {{ film.show_soon_from_date|date:"D d" }}</span>
                                {% else %}
                                <span class="badge badge-info text-center" style="font-size: 0.9em;">Зараз в кіно</span>
                                {% endif %}
                                <img class="card-img-top" src="{{ film.poster.url }}" alt="no_photo">
                                <div class="card-body">
                                    <a href="{{ film.get_absolute_url }}" class="nav-link"><p class="card-title">{{ film.title }}</p></a>
                                    <button class="btn btn-success" type="button">Купити квиток</button>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="tab-pane fade" id="list-profile" role="tabpanel" aria-labelledby="list-profile-list">
                    <div class="card-desk">
                        {% for film in films_soon %}
                            <div class="card" style="width: 15rem;">
                                {% if film.show_soon %}
                                <span class="badge badge-warning text-center" style="font-size: 0.9em;">В прокаті з {{ film.show_soon_from_date|date:"D d" }}</span>
                                {% endif %}
                                <img class="card-img-top" src="{{ film.poster.url }}" alt="no_photo">
                                <div class="card-body">
                                    <a href="{{ film.get_absolute_url }}" class="nav-link"><p class="card-title">{{ film.title }}</p></a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/theater/news.html
{% extends 'base.html' %}
{% load static %}


<!-- style="height: 40vh; background-position: center; background-image: url({% static 'img/novyny.png' %});" -->
{% block content %}
    <div class="container col-10">
        <div class="header-img" >
            <img src="{% static 'img/novyny.png' %}" alt="" class="col-12">
        </div>
        <div class="main-block row">
            <div class="news-block col-9">
                <h4 class="header-4 text-center">Новини</h4>
                <div class="news-desk col-12">
                    {% for item in news %}
                        <a href="{{ item.get_absolute_url }}" class="nav-link"><div class="card" style="height: 450px; width: 300px;">
                            <div class="badge-div text-center">
                                <span class="badge badge-info m-0"><big>{{ item.date|date:"d M Y H:i" }}</big></span>
                                <span class="badge badge-primary m-0"><big>Guliver</big></span>
                            </div>
                            <img class="card-img-top" src="{{ item.image.url }}" alt="">
                            <div class="card-body">
                                <h5 class="card-title">{{ item.title }}</h5>
                                <p class="card-text">{{ item.get_short_body }}...</p>
                            </div>
                        </div></a>
                    {% endfor %}
                </div>
                <nav aria-label="Page navigation example" class="mt-3">
                    <ul class="pagination justify-content-center">
                      <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">Previous</a>
                      </li>
                      <li class="page-item"><a class="page-link" href="#">1</a></li>
                      <li class="page-item"><a class="page-link" href="#">2</a></li>
                      <li class="page-item"><a class="page-link" href="#">3</a></li>
                      <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                      </li>
                    </ul>
                  </nav>
            </div>
            <div class="right-side-block col m-5" style="height: 500px; background-color: burlywood;">left-side-baner</div>
        </div>
    </div>
    
{% endblock content %}